"""empty message

Revision ID: 22b085fdf2cf
Revises: ec24354781af
Create Date: 2020-09-21 21:08:09.105514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b085fdf2cf'
down_revision = 'ec24354781af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutors', 'about_me',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutors', 'about_me',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
