"""empty message

Revision ID: c9bbd60ec2f0
Revises: 01fde7eff7e4
Create Date: 2020-08-10 17:26:09.909941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bbd60ec2f0'
down_revision = '01fde7eff7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tutor_category_tutor_id_fkey', 'tutor_category', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_category', 'tutors', ['tutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor_category', type_='foreignkey')
    op.create_foreign_key('tutor_category_tutor_id_fkey', 'tutor_category', 'users', ['tutor_id'], ['id'])
    # ### end Alembic commands ###
