"""empty message

Revision ID: d3faf1ebafcc
Revises: 93fd1751a8cd
Create Date: 2020-09-03 15:48:05.448026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3faf1ebafcc'
down_revision = '93fd1751a8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('title', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'title')
    # ### end Alembic commands ###
